### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ofelizestevez** [ofelizestevez/Cinematic#1]
- [ ] ContentSettings conditional
- [ ] Clean Code Lololol (very slowly, crawl through)
- [ ] Make a page state that's for rendered page
- [ ] Start Implementing enums where useful
- [ ] Add Content
- [ ] Add Content Editing
- [ ] Add Styling Editing
- [ ] Finish Theme Settings Page
- [ ] Add Custom Theme functionality
- [ ] Create a general settings page where the user can make a string that they can then copy to another computer and keep their same settings w/ lz-string
- [ ] Error Notifications
